#!/bin/bash

readonly CURRENT_KES_PERIOD=318

cardano-cli node key-gen-KES \
--verification-key-file ./1pc/hot.vkey \
--signing-key-file ./1pc/hot.skey

cardano-hw-cli node issue-op-cert \
--kes-verification-key-file ./1pc/hot.vkey \
--hw-signing-file ./1pc/cold.hwsfile \
--operational-certificate-issue-counter ./1pc/cold.counter \
--kes-period "${CURRENT_KES_PERIOD}" \
--out-file ./1pc/op.cert

echo "${CURRENT_KES_PERIOD}" > ./1pc/kes.start
